name: Test Project
on:
  workflow_dispatch:
  push:
    branches: develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Get code
        uses: actions/checkout@v4

      - run: |
          echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
          echo "ğŸ This job's status is ${{ job.status }}."

      - name: Set up JDK and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
#          cache: maven

#      - name: Cache local Maven repository
#        id: cache
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#
#      - name: Install dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: mvn package -DskipTests=true

      - name: Check maven version
        run: mvn -version

      - name: Grant permissions
        run: |
          chown root mvnw
          chmod +S mvnw
          chown root mvnw.cmd
          chmod +S mvnw.cmd

      - name: Run the Maven verify phase
#        continue-on-error: true
        run: mvn --batch-mode test -X -Dtest=RegistrationTest
#          docker run -d -p 25:3025 greenmail/standalone:2.1.0-alpha-3
#          mvn --batch-mode test -X -Dtest=RegistrationTest -Dgreenmail.startup.timeout=10000
#        run: mvn --batch-mode test -X -Dtest=FeedbackSubmissionTest
      - name: Check folders
        run: ls
