name: Test Project
on:
  workflow_dispatch:
  push:
    branches: develop
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk-slim
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Github object is ${{ toJSON(github) }}"

      - name: Install Maven
        run: |
          apt-get update -qy
          apt-get install -y maven
          mvn -version

      - name: Get code
        uses: actions/checkout@v4

      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      - name: Run the Maven verify phase
        run: mvn --batch-mode verify
