name: Test project
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      env:
        description: The environment name
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk-slim
    steps:
      - name: Install Maven
        run: |
          apt-get update -qy
          apt-get install -y maven
          mvn -version

      - run: echo "Testing code on ${{ env.ENV }} environment"

      - name: Get code
        uses: actions/checkout@v4

      - run: echo "üí° The {{ env.REPOSITORY }} repository has been cloned to the runner."

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Resolve dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mvn dependency:go-offline -B

      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."

      - name: Run tests
        run: mvn test -B

      - name: Upload allure-results
        if: failure() || env.ENV == 'qat' || env.ENV == 'uat'
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results
  generate-allure-report:
    needs: test
    if: failure() || github.event.inputs.env == 'qat' || github.event.inputs.env == 'uat'
    uses: ./.github/workflows/generate-allure-report.yml
    with:
      allure-results-artifact-name: allure-results
